### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by darkdragon-001**
- Remove unused xz library
- Minor fixes in CopyEngines

### CODE REVIEW

**Comment by alphaonex86** [comment]
Hi,
The xz is used into modular version. I will look the other commit.
Cheers,

**Comment by darkdragon-001** [comment]
Where can I find _modular version_? I could not find any usage in the code...

**Comment by darkdragon-001** [comment]
I reverted the last commit.

**Comment by alphaonex86** [comment]
The modular version is user for windows, then 95% of user.

**Pull request merged**
