### PR TITLE
Add play sound feature 

### PR DESCRIPTION
**Pull request by intika**
Add a feature to play sounds

Complete.wav : Played when everything is copied fine 
Err.wav : Play when a copy of a file fail or on retry window
Error.wav : Play when the copy finish with error

the feature is in it's first release i did not code an option on the gui to enable it or disable it... also may be QSound class would provide a better performance... or maybe caching the file to avoid reading it from the disk every time... could be an improvement for future version

Note 1 : WinMM.Lib need to be added to the compiler 
for me it's 
`
win32 {
  LIBS += "C:\Program Files\Windows Kits\8.1\Lib\winv6.3\um\x86\WinMM.Lib"
}
`

Note 2 : Wav files are located on the main folder (C:\Program Files\Ultracopier\)

Note 3 : as i am coming from teracopy this feature mimic how teracopy work

### CODE REVIEW

**Comment by alphaonex86** [comment]
I have fall into the same proble, it's why I don't implement it:
Can't compil with mingw only for need for WinMM.Lib
The wav format is too big.

After I can fix the rest, it's: Lack of multiple platform code isolation by define, add the sound options (select the file, or disable sound)

**Comment by intika** [comment]
i will make a new multi-platform version later ;)

**Comment by alphaonex86** [comment]
Then I will wait this, because my script take the source from git to compil it under mingw.
Note: opus is open format and is well suited for sound as this on low bitrates.

**Comment by intika** [comment]
i did not succeed making QSound work in windows compile etc. but no sound... also tries an other cross platform audio library SFML i was pretty confident to make it work but neither that work... so i just optimized my current version and shrieked the wav files... i will check cross platform later ;)

**Pull request closed without merging**
